### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by victorv** [librato/librato-java#40]
Hi,

Upgrading to the latest Java bindings and I see the following -
>04-04 14:37:44.311 12316-12316/com.myapp W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
04-04 14:37:44.311 12316-12316/com.myapp W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
04-04 14:37:44.311 12316-12316/com.myapp W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
04-04 14:37:52.507 12316-12316/com.myapp D/AndroidRuntime: Shutting down VM

Using Android Studio 2.3 (latest) and all the latest tools.

build.gradle here -
>apply plugin: 'java'
apply plugin: 'maven'
group = 'com.librato.metrics'
version = '2.0.6'
description = """Librato Metrics API Java Library"""
sourceCompatibility = 1.6
targetCompatibility = 1.6
tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}
configurations.all {
}
repositories {
     maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
     maven { url "http://repo.maven.apache.org/maven2" }
}
dependencies {
    compile group: 'org.codehaus.jackson', name: 'jackson-mapper-asl', version:'1.9.7'
    compile group: 'org.slf4j', name: 'slf4j-api', version:'1.6.6'
    testCompile group: 'org.slf4j', name: 'slf4j-simple', version:'1.6.6'
    testCompile group: 'junit', name: 'junit-dep', version:'4.10'
    testCompile group: 'org.mockito', name: 'mockito-core', version:'1.9.5'
    testCompile group: 'org.assertj', name: 'assertj-core', version:'1.7.1'
}

Logcat -

>AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.app, PID: 29335
                                                                                java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/DatatypeConverter;
                                                                                    at com.librato.metrics.client.Authorization.base64Encode(Authorization.java:29)
                                                                                    at com.librato.metrics.client.Authorization.buildAuthHeader(Authorization.java:25)
                                                                                    at com.librato.metrics.client.LibratoClient.<init>(LibratoClient.java:45)
                                                                                    at com.librato.metrics.client.LibratoClientBuilder.build(LibratoClientBuilder.java:44)
                                                                                    at ...
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4744)
                                                                                    at android.app.ActivityThread.access$1600(ActivityThread.java:157)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5459)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.bind.DatatypeConverter" on path: DexPathList[[zip file "/data/app/com.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.app-2/lib/arm64, /data/app/com.app-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
                                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                    at com.librato.metrics.client.Authorization.base64Encode(Authorization.java:29) 
                                                                                    at com.librato.metrics.client.Authorization.buildAuthHeader(Authorization.java:25) 
                                                                                    at com.librato.metrics.client.LibratoClient.<init>(LibratoClient.java:45) 
                                                                                    at com.librato.metrics.client.LibratoClientBuilder.build(LibratoClientBuilder.java:44) 
                                                                                    at 
...
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036) 
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4744) 
                                                                                    at android.app.ActivityThread.access$1600(ActivityThread.java:157) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5459) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                                	Suppressed: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
                                                                                    at java.lang.Class.classForName(Native Method)
                                                                                    at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                    		... 20 more
                                                                                 Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

Looks like "Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.bind.DatatypeConverter" is not available on Android

http://stackoverflow.com/questions/5461127/using-jaxb-with-google-android

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/appoptics-api-java.
